export const INIT = "INIT";
export const CHANGE_URL = "CHANGE_URL";
export const UPDATE_CONTENT = "UPDATE_CONTENT";
export const IS_LOADING = "Is_LOADING";
export const RESET = "RESET";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOADING_SUCCESS = "AUTH_LOADING_SUCCESS";
export const AUTH_LOADING_FAIL = "AUTH_LOADING_FAIL";

export const AUTH_CHECK = "AUTH_CHECK";
export const RESOLVE_PASSWORD_SUCCESS = "RESOLVE_PASSWORD_SUCCESS";
export const RESOLVE_PASSWORD_FAIL = "RESOLVE_PASSWORD_FAIL";
export const TYPING_PASSWORD = "TYPING_PASSWORD";
export const SET_PASSWORD = "SET_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";

export const UPDATE_FAIL = "UPDATE_FAIL";
export const CHANGE_SUCCESS = "CHANGE_SUCCESS";
